package main;

import java.text.DecimalFormat;


//import org.springframework.boot.autoconfigure.SpringBootApplication;

//@SpringBootApplication
public class Testes {

//	@Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//private UserRepository userRepository;
//@Autowired private static JogoRepository jogoRepository;
//@Autowired private JogoClienteRepository jogoClienteRepository;
//@Autowired private ClienteRepository clienteRepository;
//@Resource private ClienteRepositoryJPA clienteRepositoryJPA;
//@Autowired private PlataformaRepository plataformaRepository;

	public static void main(String[] args) {
		double minLat = -90.00;
	    double maxLat = 90.00;      
	    double latitude = minLat + (double)(Math.random() * ((maxLat - minLat) + 1));
	    double minLon = 0.00;
	    double maxLon = 180.00;     
	    double longitude = minLon + (double)(Math.random() * ((maxLon - minLon) + 1));
	    DecimalFormat df = new DecimalFormat("#.#####");        
	    System.out.println("latitude:longitude --> " + df.format(latitude) + "," + df.format(longitude));

	    

	}
}
