package main;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.io.ParseException;
import com.vividsolutions.jts.io.WKTReader;

import main.repositorio.ClienteRepositoryJPA;


//import org.springframework.boot.autoconfigure.SpringBootApplication;

//@SpringBootApplication
public class Testes {
	
	

//	@Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//private UserRepository userRepository;
//@Autowired private static JogoRepository jogoRepository;
//@Autowired private JogoClienteRepository jogoClienteRepository;
//@Autowired private ClienteRepository clienteRepository;
@Autowired private static ClienteRepositoryJPA clienteRepositoryJPA;
//@Autowired private PlataformaRepository plataformaRepository;

	public static void main(String[] args) {
			try {
				
				WKTReader reader = new WKTReader();
				Geometry p1= reader.read("Point(0 0.002)");
				Geometry p2= reader.read("Point(2 0.01)");
			
//		System.out.println(p1.met.distance(p2)* (Math.PI / 180) * 6378137);
				System.out.println(getDistancia(Double.valueOf(0),Double.valueOf(0.002),Double.valueOf(2),Double.valueOf(0.01)));
	
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
	
	public static double getDistancia(double latitude, double longitude, double latitudePto, double longitudePto){
	    double dlon, dlat, a, distancia;
	    dlon = longitudePto - longitude;
	    dlat = latitudePto - latitude;
	    a = Math.pow(Math.sin(dlat/2),2) + Math.cos(latitude) * Math.cos(latitudePto) * Math.pow(Math.sin(dlon/2),2);
	    distancia = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
//		return 6378140 * distancia; /* 6378140 is the radius of the Earth in meters*/
	    return 111194.682*distancia;
	}


	
}
